#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
#
Name     : R-Iso
Version  : 0.0.21
Release  : 52
URL      : https://cran.r-project.org/src/contrib/Iso_0.0-21.tar.gz
Source0  : https://cran.r-project.org/src/contrib/Iso_0.0-21.tar.gz
Summary  : Functions to Perform Isotonic Regression
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-Iso-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
isotonic regression; bivariate isotonic regression
	     with linear order on both variables.

%package lib
Summary: lib components for the R-Iso package.
Group: Libraries

%description lib
lib components for the R-Iso package.


%prep
%setup -q -n Iso
pushd ..
cp -a Iso buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1696264647

%install
export SOURCE_DATE_EPOCH=1696264647
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/Iso/DESCRIPTION
/usr/lib64/R/library/Iso/INDEX
/usr/lib64/R/library/Iso/Meta/Rd.rds
/usr/lib64/R/library/Iso/Meta/data.rds
/usr/lib64/R/library/Iso/Meta/features.rds
/usr/lib64/R/library/Iso/Meta/hsearch.rds
/usr/lib64/R/library/Iso/Meta/links.rds
/usr/lib64/R/library/Iso/Meta/nsInfo.rds
/usr/lib64/R/library/Iso/Meta/package.rds
/usr/lib64/R/library/Iso/Meta/vignette.rds
/usr/lib64/R/library/Iso/NAMESPACE
/usr/lib64/R/library/Iso/R/Iso
/usr/lib64/R/library/Iso/R/Iso.rdb
/usr/lib64/R/library/Iso/R/Iso.rdx
/usr/lib64/R/library/Iso/data/Rdata.rdb
/usr/lib64/R/library/Iso/data/Rdata.rds
/usr/lib64/R/library/Iso/data/Rdata.rdx
/usr/lib64/R/library/Iso/doc/algorithm.R
/usr/lib64/R/library/Iso/doc/algorithm.Rnw
/usr/lib64/R/library/Iso/doc/algorithm.pdf
/usr/lib64/R/library/Iso/doc/index.html
/usr/lib64/R/library/Iso/help/AnIndex
/usr/lib64/R/library/Iso/help/Iso.rdb
/usr/lib64/R/library/Iso/help/Iso.rdx
/usr/lib64/R/library/Iso/help/aliases.rds
/usr/lib64/R/library/Iso/help/paths.rds
/usr/lib64/R/library/Iso/html/00Index.html
/usr/lib64/R/library/Iso/html/R.css
/usr/lib64/R/library/Iso/makefor
/usr/lib64/R/library/Iso/pava.r
/usr/lib64/R/library/Iso/ufit.r
/usr/lib64/R/library/Iso/unimode.r

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/Iso/libs/Iso.so
/usr/lib64/R/library/Iso/libs/Iso.so.avx2
/usr/lib64/R/library/Iso/libs/Iso.so.avx512
